### ISSUE TITLE
Ignore Dockerfile and Makefile by default

### ISSUE THREAD

**Issue by abtin** [astrocorp42/flint#4]
Thanks for the nice idea. I'm going to use and recommend flint.

Should it by default ignore known files that are commonly used by go projects? Or perhaps, they can be listed as part of ignored files when executing flint init?
 
$ flint
Dockerfile: [snake_case] alphanumeric characters should be lower cased
Makefile: [snake_case] alphanumeric characters should be lower cased

**Comment by z0mbie42** [comment]
Added in fbf09a1f870209aa50762ec3acecaa0dd9eb6a59
